# Generated by Django 5.1.6 on 2025-02-14 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits and start with 9.",
                        regex="^9\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits and start with 9.",
                        regex="^9\\d{9}$",
                    )
                ],
            ),
        ),
    ]
