# Generated by Django 5.1.6 on 2025-02-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_emergency_contact_employee_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="annual_leave_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="sick_leave_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
