# Generated by Django 5.1.6 on 2025-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employee_annual_leave_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="annual_leave_balance",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name="employee",
            name="sick_leave_balance",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
