# Generated by Django 5.1.6 on 2025-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_annual_leave_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
