# Generated by Django 5.1.6 on 2025-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_employee_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="performance_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
