# Generated by Django 5.1.6 on 2025-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_employee_performance_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="face_model_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
