# Generated by Django 5.1.6 on 2025-03-23 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_attendance_date_attendance_time_in_and_more"),
        ("department", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                ("time_in", models.TimeField(null=True)),
                ("time_out", models.TimeField(null=True)),
                ("method", models.CharField(max_length=10)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.attendance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("department_name", models.CharField(max_length=100)),
                ("active_employees_count", models.IntegerField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                (
                    "leave_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LateComerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("late_time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("leave_balance", models.DecimalField(decimal_places=2, max_digits=5)),
                ("performance_rating", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
