# Generated by Django 5.1.6 on 2025-03-11 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_initial"),
        ("notifications", "0002_announcement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attended", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="department.department"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to="department.department"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
