# Generated by Django 5.1.6 on 2025-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_announcement_notification_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="select_all_departments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="select_all_employees",
            field=models.BooleanField(default=False),
        ),
    ]
