# Generated by Django 5.1.6 on 2025-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_date_attendance_time_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                blank=True, default="Absent", max_length=20, null=True
            ),
        ),
    ]
